from algo.tn_reduction.kagome_to_core import reduce_full_kagome_to_core
from algo.tn_reduction.core_to_mode import reduce_core_to_mode
from algo.tn_reduction.mode_to_edge import reduce_mode_to_edge_and_env