class BPError(Exception):...
class BPNotConvergedError(BPError):...

class ITEError(Exception):...
class TensorNetworkError(Exception): ...

class LatticeError(ValueError): ...
class DirectionError(ValueError): ...
class OutsideLatticeError(LatticeError): ...